/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaUsuario;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author arceb
 */
public class ItemPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ItemPeliculas
     */
    private Pelicula pelicula;
    private PeliculaData peliData;
    
    private Color colorOriginalFondo;
    private Border bordeOriginal;
    
    public ItemPeliculas(Pelicula pelicula, PeliculaData peliData) {
        this.peliData = peliData;
        this.pelicula = pelicula;       
        
        this.setLayout(new BorderLayout(10,10));
        
        this.colorOriginalFondo = this.getBackground();
        this.bordeOriginal = BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1);
        this.setBorder(bordeOriginal);
        
        JLabel labelImagen = new JLabel();
        
        try {
            ImageIcon icono = new ImageIcon(pelicula.getRutaImagen());
            Image img = icono.getImage().getScaledInstance(-1, 150, Image.SCALE_SMOOTH);
            labelImagen.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            labelImagen.setText("Sin imagen");
        }
        this.add(labelImagen, BorderLayout.WEST);
        
         JPanel panelDatos = new JPanel();
        panelDatos.setLayout(new BoxLayout(panelDatos, BoxLayout.Y_AXIS));
        
        JLabel labelTitulo = new JLabel(pelicula.getTitulo());
        labelTitulo.setFont(new Font("Arial", Font.BOLD, 18));
        
        JLabel labelDirector = new JLabel("Director: " + pelicula.getDirector());
        JLabel labelGenero = new JLabel("Genero: " + pelicula.getGenero());
        JLabel labelActores = new JLabel("Actores: " + pelicula.getActores());
        JLabel labelOrigen = new JLabel("Origen: " + pelicula.getOrigen());
        JLabel labelEstreno = new JLabel("Fecha de estreno: " + pelicula.getEstreno());
        
        panelDatos.add(labelTitulo);
        panelDatos.add(labelDirector);
        panelDatos.add(labelGenero);
        panelDatos.add(labelActores);
        panelDatos.add(labelOrigen);
        panelDatos.add(labelEstreno);
        
        this.add(panelDatos, BorderLayout.CENTER);
        
        
        
    }
        
    public Pelicula getPelicula() {
            return this.pelicula;
        }
    
    public void setSeleccionado(boolean seleccionado){
        if(seleccionado){
            this.setBackground(new Color(220, 235, 255));
            this.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
            this.setOpaque(true);
        
        }else{
            this.setBackground(colorOriginalFondo);
            this.setBorder(bordeOriginal);
            this.setOpaque(false);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
