/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaUsuario;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author arceb
 */
public class PanelListaPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form PanelListaPeliculas
     */
    PeliculaData peliculaData;
        
     private ItemPeliculas panelSeleccionadoActual = null;
    public PanelListaPeliculas() {
        initComponents();
        this.peliculaData = new PeliculaData();
        
        jbSiguiente.setEnabled(false);
        cargarPeliculasEnLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelLista = new javax.swing.JScrollPane();
        panelLista = new javax.swing.JPanel();
        jbSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfFiltrarPorTitulo = new javax.swing.JTextField();

        panelLista.setLayout(new javax.swing.BoxLayout(panelLista, javax.swing.BoxLayout.Y_AXIS));
        jScrollPanelLista.setViewportView(panelLista);

        jbSiguiente.setText("Siguiente");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtrar por titulo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSiguiente)
                .addGap(112, 112, 112))
            .addComponent(jScrollPanelLista)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfFiltrarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(904, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfFiltrarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSiguiente)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
        // TODO add your handling code here:
        Pelicula peliculaElegida = panelSeleccionadoActual.getPelicula();
        
        JPanel panelContenedor = (JPanel) this.getParent();
        
        CardLayout cl = (CardLayout) panelContenedor.getLayout();
        
        cl.show(panelContenedor, "Funcion");
    }//GEN-LAST:event_jbSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPanelLista;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JTextField jtfFiltrarPorTitulo;
    private javax.swing.JPanel panelLista;
    // End of variables declaration//GEN-END:variables

      private void cargarPeliculasEnLista(){
          panelLista.removeAll();
          
          List<Pelicula> peliculas = peliculaData.listarPeliculasCartelera();
          
          for (Pelicula p : peliculas) {
              ItemPeliculas itemPanel = new ItemPeliculas(p, peliculaData);
              
              itemPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                  @Override
                  public void mouseClicked(java.awt.event.MouseEvent evt){
                      
                      if(panelSeleccionadoActual != null){
                          panelSeleccionadoActual.setSeleccionado(false);
                      }
                      
                      itemPanel.setSeleccionado(true);
                      
                      panelSeleccionadoActual = itemPanel;
                      
                      jbSiguiente.setEnabled(true);
                  
                  }
              });
              panelLista.add(itemPanel);
          }
          
          panelLista.revalidate();
          panelLista.repaint();
      }


}


