/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaUsuario;

import Modelo.Pelicula;
import Modelo.Sala;
import Persistencia.PeliculaData;
import Persistencia.SalaData;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import static javax.management.Query.value;
import javax.swing.JPanel;

/**
 *
 * @author arceb
 */
public class PanelListaPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form PanelListaPeliculas
     */
    PeliculaData peliculaData;
        
     private ItemPeliculas panelSeleccionadoActual = null;
     SalaData salaData = new SalaData();
    public PanelListaPeliculas() {
        initComponents();
        this.peliculaData = new PeliculaData();
        
        jbSiguiente.setEnabled(false);
        actualizarListaPeliculas();
        cargarSalasEnComboBox();
        
        
        jcbSalas.addActionListener((ActionEvent e) -> {
            actualizarListaPeliculas();
            
        }
        );
        
        jtfBuscarNombre.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                actualizarListaPeliculas();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelLista = new javax.swing.JScrollPane();
        panelLista = new javax.swing.JPanel();
        jbSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfBuscarNombre = new javax.swing.JTextField();
        jLabelSalas = new javax.swing.JLabel();
        jcbSalas = new javax.swing.JComboBox<>();
        jbLimpiarFiltros = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        panelLista.setLayout(new javax.swing.BoxLayout(panelLista, javax.swing.BoxLayout.Y_AXIS));
        jScrollPanelLista.setViewportView(panelLista);

        jbSiguiente.setText("Siguiente");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtrar por titulo:");

        jLabelSalas.setText("Filtrar por salas");

        jbLimpiarFiltros.setText("Limpiar");
        jbLimpiarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarFiltrosActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonCerrar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelLista)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbSiguiente)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabelSalas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE)
                        .addComponent(jbLimpiarFiltros)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalas)
                    .addComponent(jcbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiarFiltros))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSiguiente)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
        // TODO add your handling code here:
        Pelicula peliculaElegida = panelSeleccionadoActual.getPelicula();
     
        
        JPanel panelContenedor = (JPanel) this.getParent();
        
        CardLayout cl = (CardLayout) panelContenedor.getLayout();
        
        for (Component comp : panelContenedor.getComponents()) {
            if(comp instanceof PanelFunciones){
                PanelFunciones panelFun = (PanelFunciones) comp;
                
                panelFun.cargarFuncionesParaPelicula(peliculaElegida);
                
                break;
            }
                
        }
        
        cl.show(panelContenedor, "Funcion");
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void jbLimpiarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarFiltrosActionPerformed
        // TODO add your handling code here:
        jtfBuscarNombre.setText("");
        jcbSalas.setSelectedIndex(0);
        actualizarListaPeliculas();
    }//GEN-LAST:event_jbLimpiarFiltrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSalas;
    private javax.swing.JScrollPane jScrollPanelLista;
    private javax.swing.JButton jbLimpiarFiltros;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JComboBox<Sala> jcbSalas;
    private javax.swing.JTextField jtfBuscarNombre;
    private javax.swing.JPanel panelLista;
    // End of variables declaration//GEN-END:variables

      private void actualizarListaPeliculas(){
          panelLista.removeAll();
          
          String nombre = jtfBuscarNombre.getText();
          Sala salaSeleccionada = (Sala) jcbSalas.getSelectedItem();
          
          Integer idSala = (salaSeleccionada != null) ? salaSeleccionada.getIdSala() : null;
          
          panelSeleccionadoActual = null;
          
          
          List<Pelicula> peliculas = peliculaData.filtrarPeliculas(nombre, idSala);
          
          for (Pelicula p : peliculas) {
              ItemPeliculas itemPanel = new ItemPeliculas(p, peliculaData);
              
              itemPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                  @Override
                  public void mouseClicked(java.awt.event.MouseEvent evt){
                      
                      if(panelSeleccionadoActual != null){
                          panelSeleccionadoActual.setSeleccionado(false);
                      }
                      
                      itemPanel.setSeleccionado(true);
                      
                      panelSeleccionadoActual = itemPanel;
                      
                      jbSiguiente.setEnabled(true);
                  
                  }
              });
              panelLista.add(itemPanel);
          }
          
          panelLista.revalidate();
          panelLista.repaint();
      }
      
      
      private void cargarSalasEnComboBox(){
          jcbSalas.removeAllItems();
          
          jcbSalas.addItem(null);
          
          List<Sala> salas = salaData.listarSalas();
          for (Sala s : salas) {
              jcbSalas.addItem(s);
          }
           
      }
      
  }




