/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Pelicula;
import Modelo.TicketCompra;
import Persistencia.PeliculaData;
import Persistencia.TicketCompraData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paula
 */
public class GestionTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionTicket
     */
    
    
    
    PeliculaData peliculaData = new PeliculaData();
    DefaultTableModel modelo = new DefaultTableModel();
    
    TicketCompraData ticketCompraData = new TicketCompraData();
    public GestionTicket() {
        initComponents();
        cargarPeliculas();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTickets = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPeliculas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonPorPelicula = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButtoPorFecha = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTableTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTickets);

        jLabel1.setText("Gestion Tickets");

        jLabel2.setText("Buscar por pelicula");

        jButtonPorPelicula.setText("Buscar");
        jButtonPorPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorPeliculaActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar por fecha");

        jButtoPorFecha.setText("Buscar");
        jButtoPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoPorFechaActionPerformed(evt);
            }
        });

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("id");

        jTextField1.setText("jTextField1");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtoPorFecha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonPorPelicula)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(9, 9, 9))
                                            .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(32, 32, 32)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPorPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtoPorFecha))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPorPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorPeliculaActionPerformed
        Pelicula pelicula = (Pelicula) jComboBoxPeliculas.getSelectedItem();
        modelo.setRowCount(0);
        
        
        
        for(TicketCompra t : ticketCompraData.ListarTicketsPorPelicula(pelicula.getIdPelicula())){
            
            
            //prueba de error!!!!!----------------------
          /*  if (t == null) {
        System.out.println("Ticket nulo");
        continue;
    }
    if (t.getComprador() == null) {
        System.out.println("Comprador nulo en ticket ID " + t.getIdTicket());
        continue;
    }
    if (t.getDetalleticket() == null) {
        System.out.println("Detalle nulo en ticket ID " + t.getIdTicket());
        continue;
    }
    if (t.getDetalleticket().getFuncion() == null) {
        System.out.println("Función nula en ticket ID " + t.getIdTicket());
        continue;
    }
    if (t.getDetalleticket().getFuncion().getPelicula() == null) {
        System.out.println("Película nula en función ID " + t.getDetalleticket().getFuncion().getIdFuncion());
        continue;
    }*/
    
    //--------------------------------------------------------------------
             modelo.addRow(new Object[]{
            t.getIdTicket(),
            t.getComprador().getNombre(),
            t.getDetalleticket().getFuncion().getPelicula().getTitulo(),
            t.getFechaCompra(),
            t.getMonto()
        });
        }
    }//GEN-LAST:event_jButtonPorPeliculaActionPerformed

    private void jButtoPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoPorFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoPorFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoPorFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPorPelicula;
    private javax.swing.JComboBox<Pelicula> jComboBoxPeliculas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTickets;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

private void cargarPeliculas(){
    
    jComboBoxPeliculas.removeAllItems();
    for (Pelicula peli : peliculaData.listarPeliculas()){
        jComboBoxPeliculas.addItem(peli);
    }
    
}


private void armarCabecera(){
    modelo.addColumn("ID Ticket");
    modelo.addColumn("Comprador");
    modelo.addColumn("Pelicula");
    modelo.addColumn("Fecha de Compra");
   // modelo.addColumn("Fecha Funcion");
   
    modelo.addColumn("Monto");
    
    //modelo.addColumn("Sala");
    //modelo.addColumn("Butacas");
    
    jTableTickets.setModel(modelo);
}



}
