/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import Persistencia.CompradorData;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JDesktopPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author arceb
 */
public class ItemsCompradores extends javax.swing.JPanel {

    /**
     * Creates new form ListaCompradores
     */
    private Comprador comprador;
    private CompradorData compradorData;
    
    
    public ItemsCompradores(Comprador comprador, CompradorData compradorData) {
        initComponents();
        this.comprador = comprador;
        this.compradorData = compradorData;
        
        this.setLayout(new BorderLayout(10, 10));
        this.setMaximumSize(new java.awt.Dimension(32767, 120));
        this.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));
        
       JPanel panelDatos = new JPanel();
       
       panelDatos.setLayout(new BoxLayout(panelDatos, BoxLayout.Y_AXIS));
       panelDatos.setBorder(new EmptyBorder(10, 10, 10, 10));
       
       JLabel labelNombre = new JLabel(comprador.getNombre());
       labelNombre.setFont(new Font("Arial", Font.BOLD, 18));
       
       JLabel labelDni = new JLabel("DNI: " + comprador.getDni());
       JLabel medioDePago = new JLabel("Medio de pago: " + comprador.getMedioDePago());
       JLabel fechaDeNacimiento = new JLabel("Fecha de nacimiento: " +  comprador.getFechaNac());
       
       panelDatos.add(labelNombre);
       panelDatos.add(labelDni);
       panelDatos.add(medioDePago);
       panelDatos.add(fechaDeNacimiento);
       this.add(panelDatos, BorderLayout.CENTER);
       
       JPanel panelBotones = new JPanel(new GridLayout(2, 2, 5, 5));
       panelBotones.setBorder(new EmptyBorder(5, 5, 5, 5));
       
        JButton btnActualizar = new JButton("Actualizar");
        JButton btnEliminar = new JButton("Eliminar");
        
        btnActualizar.addActionListener(e -> {
            //Busca al jdesktopPane mas cercano para mostrar la ventana que queremos abrir
            JDesktopPane desktopPane = (JDesktopPane) SwingUtilities.getAncestorOfClass(JDesktopPane.class, this);
            
            //Si encuentra un desktopPane entra a la condicion
            if(desktopPane != null){
                PantallaRegistro reg = new PantallaRegistro();
                desktopPane.add(reg);
                reg.setVisible(true);
                
                //establece la ubicacion de la nueva ventana que queremos abrir
                reg.setLocation(
                        (desktopPane.getWidth() - reg.getWidth()) / 2,
                        (desktopPane.getHeight() - reg.getHeight()) / 2
                );
            }
            
        
        });
        
        btnEliminar.addActionListener(e -> {
            int r = JOptionPane.showConfirmDialog(this, "¿Seguro que sea eliminar a " + comprador.getNombre() + " de la base de datos?",
                    "Confirmar Eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
            if(r == JOptionPane.YES_OPTION){
                compradorData.eliminarComprador(comprador.getIdComprador());
                this.getParent().remove(this);
                this.getParent().revalidate();
                this.getParent().repaint();
            }
        
        });
        
        panelBotones.add(btnActualizar);
        panelBotones.add(btnEliminar);
        
        this.add(panelBotones, BorderLayout.EAST);
        
        
               
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
