/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.util.List;

/**
 *
 * @author arceb
 */
public class ListarPeliculas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarPeliculas
     */
    private PeliculaData peliculaData;
    public ListarPeliculas() {
        initComponents();
        this.peliculaData = new PeliculaData();
        cargarPeliculas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelContenedor = new javax.swing.JPanel();

        PanelContenedor.setLayout(new javax.swing.BoxLayout(PanelContenedor, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(PanelContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarPeliculas(){
        PanelContenedor.removeAll();
        
        List<Pelicula> peliculas = peliculaData.listarPeliculasCartelera();
        
        for(Pelicula p : peliculas){
            
                PanelItemPelicula itemPanel = new PanelItemPelicula(p, peliculaData);
                PanelContenedor.add(itemPanel);
        
        }
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }

}
