/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author paula
 */
public class PanelItemPeliculaEstreno extends javax.swing.JPanel {

    /**
     * Creates new form PanelItemPeliculaEstreno
     */
     private Pelicula pelicula;
    private PeliculaData peliData;
    public PanelItemPeliculaEstreno(Pelicula pelicula, PeliculaData peliData) {
        
        
         this.pelicula = pelicula;
        this.peliData = peliData;
        
        //---------------------------Imagen-----------------------------------------------
        this.setLayout(new BorderLayout(10,10));
        this.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));
        
        JLabel labelImagen = new JLabel();
        
        try {
            ImageIcon icono = new ImageIcon(pelicula.getRutaImagen());
            Image img = icono.getImage().getScaledInstance(-1, 150, Image.SCALE_SMOOTH);
            labelImagen.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            labelImagen.setText("Sin imagen");
        }
        this.add(labelImagen, BorderLayout.WEST);
        
        //-----------------------------datos-------------------------------------------------
        
        JPanel panelDatos = new JPanel();
        panelDatos.setLayout(new BoxLayout(panelDatos, BoxLayout.Y_AXIS));
        
        JLabel labelTitulo = new JLabel(pelicula.getTitulo());
        labelTitulo.setFont(new Font("Arial", Font.BOLD, 18));
        
        JLabel labelDirector = new JLabel("Director: " + pelicula.getDirector());
        JLabel labelGenero = new JLabel("Genero: " + pelicula.getGenero());
        JLabel labelActores = new JLabel("Actores: " + pelicula.getActores());
        JLabel labelOrigen = new JLabel("Origen: " + pelicula.getOrigen());
        
        
        panelDatos.add(labelTitulo);
        panelDatos.add(labelDirector);
        panelDatos.add(labelGenero);
        panelDatos.add(labelActores);
        panelDatos.add(labelOrigen);
        
        
        this.add(panelDatos, BorderLayout.CENTER);
        
        //--------------------------acciones-------------------------------------------------
        JPanel panelFecha = new JPanel();
        panelFecha.setLayout(new BoxLayout(panelFecha, BoxLayout.Y_AXIS));
        
        panelFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 20));
        
        JLabel labelTituloFecha = new JLabel("ESTRENO");
        
        labelTituloFecha.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        labelTituloFecha.setAlignmentX(CENTER_ALIGNMENT);
        
        JLabel labelEstreno = new JLabel(pelicula.getEstreno().toString());
        labelEstreno.setFont(new Font("Segoe UI", Font.BOLD, 28));
        
        labelEstreno.setAlignmentX(CENTER_ALIGNMENT);
        
        panelFecha.add(javax.swing.Box.createVerticalGlue());
        panelFecha.add(labelTituloFecha);
        panelFecha.add(labelEstreno);
        panelFecha.add(javax.swing.Box.createVerticalGlue());
        
        
  
          
        this.add(panelFecha, BorderLayout.EAST);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
