/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import Persistencia.CompradorData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author franco
 */
public class PantallaRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaRegistro
     */
   CompradorData compradorData = new CompradorData();
    
    public PantallaRegistro() {
        initComponents();
        cargarMediosDePago();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jContrasenia = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jBIniciar = new javax.swing.JButton();
        jBatras = new javax.swing.JButton();
        jComboMedioDePago = new javax.swing.JComboBox<>();
        jbuttonActualizar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        jLabel1.setText("Registrarse");

        jLabel2.setText("DNI:");

        jLabel3.setText("Nombre y apellido:");

        jLabel4.setText("Fecha de nacimiento:");

        jLabel5.setText("Contraseña:");

        jContrasenia.setText("jPasswordField1");

        jLabel6.setText("Medio de pago:");

        jBIniciar.setText("Registrarse");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });

        jBatras.setText("atras");
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });

        jbuttonActualizar.setText("Actualizar");
        jbuttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActualizarActionPerformed(evt);
            }
        });

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBatras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBIniciar)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jDateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboMedioDePago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonActualizar)
                                .addComponent(jContrasenia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextDni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jComboMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIniciar)
                    .addComponent(jBatras)
                    .addComponent(jbuttonActualizar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed
        try{
            
            
            //validamos  q no haya campos vacios
            
            
            if(jTextNombre.getText().isEmpty() ||jTextDni.getText().isEmpty() || 
                    jDateNacimiento.getDate()==null || 
                    jContrasenia.getPassword().length ==0 ||
                    jComboMedioDePago.getSelectedIndex()==0){
                
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos");
                return;
            }
            
            
            Comprador comprador = new Comprador();
            comprador.setNombre(jTextNombre.getText());
            comprador.setDni(Integer.parseInt(jTextDni.getText()));
            
            
            LocalDate fechaNac = jDateNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            comprador.setFechaNac(fechaNac);
            
            comprador.setPassword(new String (jContrasenia.getPassword()));
            comprador.setMedioDePago((String)jComboMedioDePago.getSelectedItem());
            
            CompradorData compraData = new CompradorData();
            compraData.guardarComprador(comprador);
            
            
             JOptionPane.showMessageDialog(this, "Comprador registrado Correctamente");
             
             
             limpiarCampos();
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "El dni debe ser un numero valido");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error al registrar al comprador");
        
    }
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
        PantallaRegistro.this.dispose();
        
        
         
         
    }//GEN-LAST:event_jBatrasActionPerformed

    private void jbuttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActualizarActionPerformed
        // TODO add your handling code here:
        
        try {
            
            String nombre = jTextNombre.getText();
            int dni = Integer.parseInt(jTextDni.getText());
            Date fecha = jDateNacimiento.getDate();
            LocalDate fechaNacimiento = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String contrasena = new String (jContrasenia.getPassword());
            String medioPago = (String) jComboMedioDePago.getSelectedItem();
            
            Comprador c = compradorData.buscarComprador(dni);
            
                if(c == null){
                    JOptionPane.showMessageDialog(this, "No se encontro comprador con ese ID");
                }
                
                c.setDni(dni);
                c.setNombre(nombre);
                c.setFechaNac(fechaNacimiento);
                c.setPassword(contrasena);
                c.setMedioDePago(medioPago);
                
                compradorData.actualizarComprador(c);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar comprador");
        }
        
    }//GEN-LAST:event_jbuttonActualizarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
// TODO add your handling code here:
            
          if(jTextDni.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "Debe ingresar el DNI del usuario que desea buscar ");
              return;
          }
        try{
        
            
            
       int dni = Integer.parseInt(jTextDni.getText());
        
       Comprador c = compradorData.buscarComprador(dni);
       
       if(c != null){
           jTextNombre.setText(c.getNombre());
           jTextDni.setText(String.valueOf(c.getDni()));
           jDateNacimiento.setDate(java.sql.Date.valueOf(c.getFechaNac()));
           jContrasenia.setText(c.getPassword());
           jComboMedioDePago.setSelectedItem(c.getMedioDePago());
       }else{
           JOptionPane.showMessageDialog(this, "No se encontro comprador con ese dni");
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al buscar comprador");
        }
       
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jBatras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboMedioDePago;
    private javax.swing.JPasswordField jContrasenia;
    private com.toedter.calendar.JDateChooser jDateNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JButton jbuttonActualizar;
    // End of variables declaration//GEN-END:variables


    private void cargarMediosDePago(){
        jComboMedioDePago.addItem("Efectivo");
        jComboMedioDePago.addItem("Tarjeta de Debito");
        jComboMedioDePago.addItem("Tarjeta de Credito");
        jComboMedioDePago.addItem("Mercado Pago");
        jComboMedioDePago.addItem("Transferencia");
        
    }
    
    private void limpiarCampos(){
        jTextNombre.setText("");
        jTextDni.setText("");
        jDateNacimiento.setDate(null);
        jContrasenia.setText("");
        jComboMedioDePago.setSelectedIndex(0);
    }





}
