/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import VistaUsuario.PaginaPrincipal;
import VistaUsuario.Precios;




/**
 *
 * @author franco
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    private Comprador usuarioActual;
    public PantallaPrincipal(Comprador usuario) {
        initComponents();   
        desktopConFondo2.setLayout(null);
        
        desktopConFondo2.setBackground(java.awt.Color.decode("#2C3E50"));
        
        this.usuarioActual = usuario;
        configurarPermisos();
        
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    private PantallaPrincipal() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopConFondo2 = new Vistas.DesktopConFondo();
        jButtonPelisEnCartelera = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonProximosEstrenos = new javax.swing.JButton();
        jButtonPrecios = new javax.swing.JButton();
        jmenuBar = new javax.swing.JMenuBar();
        jmPeliculas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuListaPelis = new javax.swing.JMenuItem();
        jMenuItemEstadistica = new javax.swing.JMenuItem();
        jmFunciones = new javax.swing.JMenu();
        jMenuFuncion = new javax.swing.JMenuItem();
        jMenuSala = new javax.swing.JMenuItem();
        jMenuItemTicket = new javax.swing.JMenuItem();
        jMenuItemGestionTicket = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCompradores = new javax.swing.JMenuItem();
        jMenuItemCompradorLista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPelisEnCartelera.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButtonPelisEnCartelera.setText("Peliculas en cartelera");
        jButtonPelisEnCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPelisEnCarteleraActionPerformed(evt);
            }
        });
        desktopConFondo2.add(jButtonPelisEnCartelera);
        jButtonPelisEnCartelera.setBounds(740, 230, 180, 50);

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("¡Bienvenido a CinemaCentro!");
        desktopConFondo2.add(jLabel4);
        jLabel4.setBounds(790, 70, 330, 50);

        jButtonProximosEstrenos.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButtonProximosEstrenos.setText("Proximos estrenos");
        jButtonProximosEstrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximosEstrenosActionPerformed(evt);
            }
        });
        desktopConFondo2.add(jButtonProximosEstrenos);
        jButtonProximosEstrenos.setBounds(990, 230, 190, 50);

        jButtonPrecios.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButtonPrecios.setText("Precios");
        jButtonPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreciosActionPerformed(evt);
            }
        });
        desktopConFondo2.add(jButtonPrecios);
        jButtonPrecios.setBounds(880, 390, 150, 50);

        jmenuBar.setEnabled(false);

        jmPeliculas.setText("Peliculas");

        jMenuItem1.setText("Agregar peliculas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmPeliculas.add(jMenuItem1);

        menuListaPelis.setText("Lista de peliculas");
        menuListaPelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaPelisActionPerformed(evt);
            }
        });
        jmPeliculas.add(menuListaPelis);

        jMenuItemEstadistica.setText("Estadisticas");
        jMenuItemEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadisticaActionPerformed(evt);
            }
        });
        jmPeliculas.add(jMenuItemEstadistica);

        jmenuBar.add(jmPeliculas);

        jmFunciones.setText("Funciones");

        jMenuFuncion.setText("Funciones");
        jMenuFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncionActionPerformed(evt);
            }
        });
        jmFunciones.add(jMenuFuncion);

        jMenuSala.setText("Sala");
        jMenuSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalaActionPerformed(evt);
            }
        });
        jmFunciones.add(jMenuSala);

        jMenuItemTicket.setText("ticket");
        jMenuItemTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTicketActionPerformed(evt);
            }
        });
        jmFunciones.add(jMenuItemTicket);

        jMenuItemGestionTicket.setText("Gestion Ticket");
        jMenuItemGestionTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionTicketActionPerformed(evt);
            }
        });
        jmFunciones.add(jMenuItemGestionTicket);

        jmenuBar.add(jmFunciones);

        jMenu1.setText("Gestion Clientes");

        jMenuItemCompradores.setText("Compradores");
        jMenuItemCompradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompradoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCompradores);

        jMenuItemCompradorLista.setText("ListaCompradores");
        jMenuItemCompradorLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompradorListaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCompradorLista);

        jmenuBar.add(jMenu1);

        setJMenuBar(jmenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopConFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopConFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PantallaPeliculas pelis = new PantallaPeliculas();
        pelis.setVisible(true);
        desktopConFondo2.add(pelis);
        desktopConFondo2.moveToFront(pelis);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuListaPelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaPelisActionPerformed
        // TODO add your handling code here:
        ListarPeliculas list = new ListarPeliculas();
        list.setVisible(true);
        desktopConFondo2.add(list);
        desktopConFondo2.moveToFront(list);
    }//GEN-LAST:event_menuListaPelisActionPerformed

    private void jMenuFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncionActionPerformed
        // TODO add your handling code here:
        VistaFuncion fun = new VistaFuncion();
        fun.setVisible(true);
        desktopConFondo2.add(fun);  
        desktopConFondo2.moveToFront(fun);
    }//GEN-LAST:event_jMenuFuncionActionPerformed

    private void jMenuSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalaActionPerformed
        // TODO add your handling code here:
        vistaSala sala = new vistaSala();
        sala.setVisible(true);
        desktopConFondo2.add(sala);
        desktopConFondo2.moveToFront(sala);
    }//GEN-LAST:event_jMenuSalaActionPerformed

    private void jButtonPelisEnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPelisEnCarteleraActionPerformed
        // TODO add your handling code here:
        PaginaPrincipal inicio = new PaginaPrincipal();
        inicio.setVisible(true);
        desktopConFondo2.add(inicio);
        desktopConFondo2.moveToFront(inicio);
       
    }//GEN-LAST:event_jButtonPelisEnCarteleraActionPerformed

    private void jMenuItemTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTicketActionPerformed
      VistaDetalleTicket ticket = new VistaDetalleTicket();
      ticket.setVisible(true);
      
      desktopConFondo2.moveToFront(ticket);
      
    }//GEN-LAST:event_jMenuItemTicketActionPerformed

    private void jMenuItemGestionTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionTicketActionPerformed
        GestionTicket gestion = new GestionTicket();
        gestion.setVisible(true);
        desktopConFondo2.add(gestion);
        desktopConFondo2.moveToFront(gestion);
    }//GEN-LAST:event_jMenuItemGestionTicketActionPerformed

    private void jMenuItemCompradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompradoresActionPerformed
        // TODO add your handling code here:
        PruebaLISTARCOMPRADORES comprador = new PruebaLISTARCOMPRADORES();
        comprador.setVisible(true);
        desktopConFondo2.add(comprador);
        desktopConFondo2.moveToFront(comprador);
    }//GEN-LAST:event_jMenuItemCompradoresActionPerformed

    private void jMenuItemCompradorListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompradorListaActionPerformed
        // TODO add your handling code here:
        ListaCompradoresPorFecha comprador = new ListaCompradoresPorFecha();
        comprador.setVisible(true);
        desktopConFondo2.add(comprador);
        desktopConFondo2.moveToFront(comprador);
    }//GEN-LAST:event_jMenuItemCompradorListaActionPerformed

    private void jMenuItemEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadisticaActionPerformed
        // TODO add your handling code here:
        PeliculasMasVistas vistas = new PeliculasMasVistas();
        vistas.setVisible(true);
        desktopConFondo2.add(vistas);
        desktopConFondo2.moveToFront(vistas);
    }//GEN-LAST:event_jMenuItemEstadisticaActionPerformed

    private void jButtonProximosEstrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximosEstrenosActionPerformed
        // TODO add your handling code here:
        Estrenos list = new Estrenos();
        list.setVisible(true);
        desktopConFondo2.add(list);
        desktopConFondo2.moveToFront(list);
    }//GEN-LAST:event_jButtonProximosEstrenosActionPerformed

    private void jButtonPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreciosActionPerformed
        // TODO add your handling code here:
        Precios precios = new Precios();
        precios.setVisible(true);
        desktopConFondo2.add(precios);
    }//GEN-LAST:event_jButtonPreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.DesktopConFondo desktopConFondo2;
    private javax.swing.JButton jButtonPelisEnCartelera;
    private javax.swing.JButton jButtonPrecios;
    private javax.swing.JButton jButtonProximosEstrenos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuFuncion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCompradorLista;
    private javax.swing.JMenuItem jMenuItemCompradores;
    private javax.swing.JMenuItem jMenuItemEstadistica;
    private javax.swing.JMenuItem jMenuItemGestionTicket;
    private javax.swing.JMenuItem jMenuItemTicket;
    private javax.swing.JMenuItem jMenuSala;
    private javax.swing.JMenu jmFunciones;
    private javax.swing.JMenu jmPeliculas;
    private javax.swing.JMenuBar jmenuBar;
    private javax.swing.JMenuItem menuListaPelis;
    // End of variables declaration//GEN-END:variables
    
    private void configurarPermisos(){
        if(usuarioActual == null){
            this.setTitle("CinemaCentro - Modo ADMINISTRADOR");
            jmenuBar.setVisible(true);
            jmenuBar.setEnabled(true);
            
            jmPeliculas.setVisible(true);
            jmFunciones.setVisible(true);
        }else{
            this.setTitle("CinemaCentro - Bienvenido " + usuarioActual.getNombre());
            jmenuBar.setVisible(false);
            jmPeliculas.setVisible(false);
            jmFunciones.setVisible(false);
        
        }
    }

}
