/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import Persistencia.CompradorData;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author franco
 */
public class PantallaRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaRegistro
     */
   
    
    public PantallaRegistro() {
        initComponents();
        cargarMediosDePago();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jContrasenia = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jBIniciar = new javax.swing.JButton();
        jBatras = new javax.swing.JButton();
        jComboMedioDePago = new javax.swing.JComboBox<>();

        jLabel1.setText("Registrarse");

        jLabel2.setText("DNI:");

        jLabel3.setText("Nombre y apellido:");

        jLabel4.setText("Fecha de nacimiento:");

        jLabel5.setText("Contraseña:");

        jContrasenia.setText("jPasswordField1");

        jLabel6.setText("Medio de pago:");

        jBIniciar.setText("Iniciar Sesion");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });

        jBatras.setText("atras");
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jDateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBatras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBIniciar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jComboMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIniciar)
                    .addComponent(jBatras))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed
        try{
            
            
            //validamos  q no haya campos vacios
            
            
            if(jTextNombre.getText().isEmpty() ||jTextDni.getText().isEmpty() || 
                    jDateNacimiento.getDate()==null || 
                    jContrasenia.getPassword().length ==0 ||
                    jComboMedioDePago.getSelectedIndex()==0){
                
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos");
                return;
            }
            
            
            Comprador comprador = new Comprador();
            comprador.setNombre(jTextNombre.getText());
            comprador.setDni(Integer.parseInt(jTextDni.getText()));
            
            
            LocalDate fechaNac = jDateNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            comprador.setFechaNac(fechaNac);
            
            comprador.setPassword(new String (jContrasenia.getPassword()));
            comprador.setMedioDePago((String)jComboMedioDePago.getSelectedItem());
            
            CompradorData compraData = new CompradorData();
            compraData.guardarComprador(comprador);
            
            
             JOptionPane.showMessageDialog(this, "Comprador registrado Correctamente");
             
             
             limpiarCampos();
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "El dni debe ser un numero valido");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error al registrar al comprador");
        
    }
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
        PantallaRegistro.this.dispose();
        
        
         
         
    }//GEN-LAST:event_jBatrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jBatras;
    private javax.swing.JComboBox<String> jComboMedioDePago;
    private javax.swing.JPasswordField jContrasenia;
    private com.toedter.calendar.JDateChooser jDateNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables


    private void cargarMediosDePago(){
        jComboMedioDePago.addItem("Efectivo");
        jComboMedioDePago.addItem("Tarjeta de Debito");
        jComboMedioDePago.addItem("Tarjeta de Credito");
        jComboMedioDePago.addItem("Mercado Pago");
        jComboMedioDePago.addItem("Transferencia");
        
    }
    
    private void limpiarCampos(){
        jTextNombre.setText("");
        jTextDni.setText("");
        jDateNacimiento.setDate(null);
        jContrasenia.setText("");
        jComboMedioDePago.setSelectedIndex(0);
    }





}
