/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Sala;
import Persistencia.SalaData;
import javax.swing.JOptionPane;

/**
 *
 * @author paula
 */
public class vistaSala extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaSala
     */
    public vistaSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JButton();
        jTextID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNroSala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadio3d = new javax.swing.JRadioButton();
        jCapacidad = new javax.swing.JSpinner();
        jRadioEstado = new javax.swing.JRadioButton();
        jBCrear = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Salas");

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel2.setText("ID Sala: ");

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel3.setText("Numero de Sala:");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel4.setText("Apta para 3D:");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel5.setText("Capacidad:");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel6.setText("Estado:");

        jRadio3d.setText("SI");

        jRadioEstado.setText("Activo");

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextID)
                            .addComponent(jTextNroSala)
                            .addComponent(jCapacidad)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadio3d)
                                    .addComponent(jRadioEstado))
                                .addGap(0, 53, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBuscar)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBActualizar)
                                .addGap(34, 34, 34)))
                        .addComponent(jBEliminar)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBuscar)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNroSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadio3d))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioEstado))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrear)
                    .addComponent(jBActualizar)
                    .addComponent(jBEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        
        SalaData salaData = new SalaData();
        
        try{
         if (jTextID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para buscar la sala.");
            return;
        }
        
         
         
         int id = Integer.parseInt(jTextID.getText());
         Sala sala = salaData.buscarSala(id);
         
         
         if (sala != null) {
            // Rellena los campos con los datos de la sala
            jTextNroSala.setText(String.valueOf(sala.getNroSala()));
            jCapacidad.setValue(sala.getCapacidad());
            jRadio3d.setSelected(sala.isApto3d());
            jRadioEstado.setSelected(sala.isEstado());
           
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna sala con ese ID.");
            limpiarCampos();
        }
        }catch(NumberFormatException e){
            
              JOptionPane.showMessageDialog(this, "El campo ID debe contener solo números.");
        }
         
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
       
        SalaData salaData = new SalaData();
        
        try {
        if (jTextNroSala.getText().isEmpty()) {
           JOptionPane.showMessageDialog(this, "Debe ingresar el número de sala.");
            return;
        }

        int numero = Integer.parseInt(jTextNroSala.getText());
        boolean apto3D = jRadio3d.isSelected();
        int capacidad = (Integer) jCapacidad.getValue();
        boolean estado = jRadioEstado.isSelected();

       if (salaData.existeNumeroSala(numero)) {
            JOptionPane.showMessageDialog(this,"Ya existe una sala con el número " + numero);
            return;
        }
        Sala nuevaSala = new Sala();
        nuevaSala.setNroSala(numero);
        nuevaSala.setApto3d(apto3D);
        nuevaSala.setCapacidad(capacidad);
        nuevaSala.setEstado(estado);

        salaData.guardarSala(nuevaSala);

        

        limpiarCampos();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un número válido para el campo 'Número de Sala'.");
    } 

    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
       
        SalaData salaData = new SalaData();
              
        try{
         if (jTextID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para buscar la sala.");
            return;
        }
         
         
         
          int id = Integer.parseInt(jTextID.getText());
          int numero = Integer.parseInt(jTextNroSala.getText());
          boolean apto3D = jRadio3d.isSelected();
          int capacidad = (Integer) jCapacidad.getValue();
          boolean estado = jRadioEstado.isSelected();
          
          
          if (salaData.existeNumeroSalaExcluyendoId(numero, id)) {
            JOptionPane.showMessageDialog(this, "Ya existe otra sala con el número ");
            return; 
         }
          
          Sala s = new Sala();
          s.setIdSala(id);
          s.setNroSala(numero);
          s.setApto3d(apto3D);
          s.setCapacidad(capacidad);
          s.setEstado(estado);
          
          
          salaData.actualizarSala(s);
          
           limpiarCampos();

        }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this, "El campo ID debe contener solo números.");
            
        }
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        
        SalaData salaData = new SalaData();
        
        
        try{
         if (jTextID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para buscar la sala.");
            return;
        }
         
         
         int id = Integer.parseInt(jTextID.getText());
         
         
         int confirm = JOptionPane.showConfirmDialog(
                this, "¿Está seguro que desea eliminar la sala con ID " + id + "?", "Confirmar eliminación",JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            salaData.eliminarSala(id);
            limpiarCampos();
        }
         
         }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this, "El campo ID debe contener solo números.");
            
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBuscar;
    private javax.swing.JSpinner jCapacidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadio3d;
    private javax.swing.JRadioButton jRadioEstado;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextNroSala;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
    jTextID.setText("");
    jTextNroSala.setText("");
    jRadio3d.setSelected(false);
    jCapacidad.setValue(0); // Valor por defecto 
    jRadioEstado.setSelected(false);
    
}



}
