/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import Modelo.DetalleTicket;
import Modelo.Funcion;
import Modelo.Lugar;
import Modelo.TicketCompra;
import Persistencia.CompradorData;
import Persistencia.DetalleTicketData;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import Persistencia.TicketCompraData;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author arceb
 */
public class VistaDetalleTicket extends javax.swing.JFrame {
    
    FuncionData funcionData = new FuncionData();
    CompradorData compradorData = new CompradorData();
    DetalleTicketData detalleData = new DetalleTicketData();
    LugarData lugarData = new LugarData();
    TicketCompraData ticketCompraData = new TicketCompraData();
    
    private List<Lugar> lugaresDisponibles = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaDetalleTicket.class.getName());
    
    

    /**
     * Creates new form VistaDetalleTicket
     */
    public VistaDetalleTicket() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cargarComboFunciones();
        cargarComboCompradores();
        
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelButacas = new javax.swing.JPanel();
        jComboBoxFuncion = new javax.swing.JComboBox<>();
        jComboBoxCompradores = new javax.swing.JComboBox<>();
        jButtonCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelButacas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelButacasLayout = new javax.swing.GroupLayout(jPanelButacas);
        jPanelButacas.setLayout(jPanelButacasLayout);
        jPanelButacasLayout.setHorizontalGroup(
            jPanelButacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanelButacasLayout.setVerticalGroup(
            jPanelButacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jComboBoxFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionActionPerformed(evt);
            }
        });

        jButtonCompra.setText("Confirmar compra");
        jButtonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompraActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione la funcion:");

        jLabel2.setText("Cliente:");

        jLabelPrecio.setText("*");

        jLabelCantidad.setText("*");

        jLabelTotal.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(872, 872, 872)
                        .addComponent(jButtonCompra))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jComboBoxFuncion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCompradores, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelButacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPrecio))
                .addGap(18, 18, 18)
                .addComponent(jLabelCantidad)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCompradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanelButacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButtonCompra)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionActionPerformed
        // TODO add your handling code here:
        
        Funcion funcionselec = (Funcion) jComboBoxFuncion.getSelectedItem();
        
        if(funcionselec != null){
            crearButacas(funcionselec.getIdFuncion());
        }
        
    }//GEN-LAST:event_jComboBoxFuncionActionPerformed

    private void jButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompraActionPerformed
        // TODO add your handling code here:
        Funcion funcionselec = (Funcion) jComboBoxFuncion.getSelectedItem();
        Comprador compradorSelec = (Comprador) jComboBoxCompradores.getSelectedItem();
        
        if(funcionselec == null || compradorSelec == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una funcion y un cliente");
            return;
        }
        
        if(lugaresDisponibles == null || lugaresDisponibles.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una butaca");
            return;
        }
        
        double precio = funcionselec.getPrecio();
        double total = precio * lugaresDisponibles.size();
        DetalleTicket detalle = new DetalleTicket();
         
            
            detalle.setFuncion(funcionselec);
            detalle.setSubtotal(precio);
            if(lugaresDisponibles.size() == 1){
                detalle.setLugar(lugaresDisponibles.get(0));
                detalle.setCantidad(null);
            }else if(lugaresDisponibles.size() == 2){
                detalle.setLugar(lugaresDisponibles.get(0));
                detalle.setCantidad(lugaresDisponibles.get(1));
            }
            
            
            detalleData.guardarDetalleTicket(detalle);
            for (Lugar lu : lugaresDisponibles) {
                lu.setEstado(false);
                lugarData.darBajaLugar(lu.getIdLugar());
        }
            
            
            
        int idDetalleGenerado = detalle.getIdDetalleTicket();
        System.out.println("Detalle guardado con ID: " + detalle.getIdDetalleTicket());
        TicketCompra ticket = new TicketCompra();
        ticket.setFechaCompra(LocalDate.now());
        ticket.setFechaFuncion(funcionselec.getHoraInicio());
        ticket.setMonto(total);
        ticket.setComprador(compradorSelec);
        ticket.setDetalleticket(detalle);
        
        ticketCompraData.guardarTicketCompra(ticket);
        
        JOptionPane.showMessageDialog(this, "Ticker creado" + " total: " + total);
        
        
        lugaresDisponibles.clear();
        
        crearButacas(funcionselec.getIdFuncion());
    }//GEN-LAST:event_jButtonCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCompra;
    private javax.swing.JComboBox<Comprador> jComboBoxCompradores;
    private javax.swing.JComboBox<Funcion> jComboBoxFuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelButacas;
    // End of variables declaration//GEN-END:variables

    private void crearButacas(int idFuncion){
        
        jPanelButacas.removeAll(); //Limpiamos el panel
        LugarData lugarData = new LugarData();
        
        List<Lugar> lugares = lugarData.buscarLugaresPorFuncion(idFuncion);
        
        int columnas = 4;
        jPanelButacas.setLayout(new GridLayout(0, columnas, 10, 10));
        
        for (Lugar lu : lugares) {
           JButton boton = new JButton(lu.getFila() + String.valueOf(lu.getNum()));
           boton.setPreferredSize(new Dimension (50, 40));
           //Si esta ocupado 
           if(!lu.isEstado()){
               boton.setBackground(Color.red);
               boton.setEnabled(false);
           }else{
               //si esta libre
               boton.setBackground(Color.GREEN);
               boton.addActionListener(e -> {if(lugaresDisponibles.contains(lu)){
                lugaresDisponibles.remove(lu);
                boton.setBackground(Color.GREEN);
               }else{
                   if(lugaresDisponibles.size() < 2){
                       lugaresDisponibles.add(lu);
                       boton.setBackground(Color.BLUE);
                   }else{
                       JOptionPane.showMessageDialog(this, "Solo puede seleccionar 2 asientos");
                   }
               }});
           } jPanelButacas.add(boton);
        } jPanelButacas.revalidate();
          jPanelButacas.repaint();
          
    }
    
    private void cargarComboFunciones(){
        jComboBoxFuncion.removeAllItems();
        List<Funcion> funcion = funcionData.listarFuncion();
        
            for (Funcion fun : funcion) {
            jComboBoxFuncion.addItem(fun);
        }
    }
    
    private void cargarComboCompradores(){
        jComboBoxCompradores.removeAllItems();
        List<Comprador> comprador = compradorData.listarCompradores();
        
        for (Comprador compra : comprador) {
            jComboBoxCompradores.addItem(compra);
        }
    
    }

}
