/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Sala;
import Persistencia.FuncionData;
import Persistencia.PeliculaData;
import Persistencia.SalaData;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author arceb
 */
public class VistaFuncion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaFuncion
     */
    FuncionData funcionData = new FuncionData();
    
    PeliculaData peliData = new PeliculaData();
    List<Pelicula> listaPelicula = peliData.listarPeliculasCartelera();
    SalaData salaData = new SalaData();
    List<Sala> listaSalas = salaData.listarSalas();
    
     
    
    
    public VistaFuncion() {
        initComponents();
        cargarPeliculas();
        cargarSalas();
       limpiarCampos();
        jButtonActualizar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
        
        SpinnerNumberModel  horaModel = new SpinnerNumberModel(12, 0, 23, 1);
        jSpinnerHora.setModel(horaModel); 
        SpinnerNumberModel minutosModel = new SpinnerNumberModel(0, 0, 59, 1);
        jSpinnerMinutos.setModel(minutosModel);
        
        JSpinner.NumberEditor numEditor = new JSpinner.NumberEditor(jSpinnerMinutos, "00");
        jSpinnerMinutos.setEditor(numEditor);  
        JSpinner.NumberEditor numEditorHora = new JSpinner.NumberEditor(jSpinnerHora, "00");
        jSpinnerHora.setEditor(numEditorHora);
        
        //---------------------Spinner de horario fin----------------
        
        SpinnerNumberModel  horaModel2 = new SpinnerNumberModel(12, 0, 23, 1);
        jSpinnerHoraFin.setModel(horaModel2);      
         SpinnerNumberModel minutosModel2 = new SpinnerNumberModel(0, 0, 59, 1);
        jSpinnerMinutosFin.setModel(minutosModel2);
        
        
        JSpinner.NumberEditor numEditor2 = new JSpinner.NumberEditor(jSpinnerMinutosFin, "00");
        jSpinnerMinutosFin.setEditor(numEditor2);  
        JSpinner.NumberEditor numEditorHora2 = new JSpinner.NumberEditor(jSpinnerHoraFin, "00");
        jSpinnerHoraFin.setEditor(numEditorHora2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboPeliculas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIdioma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton3d = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonSub = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jSpinnerMinutos = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerHoraFin = new javax.swing.JSpinner();
        jSpinnerMinutosFin = new javax.swing.JSpinner();
        jdcHoraInicio = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxSala = new javax.swing.JComboBox<>();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtoncerrar = new javax.swing.JButton();

        jLabel1.setText("Seleccionar pelicula");

        jLabel2.setText("Idioma:");

        jLabel3.setText("3d:");

        jLabel4.setText("Subtitulado:");

        jLabel5.setText("Horario de inicio:");

        jLabel6.setText("Horario de fin");

        jLabel7.setText("Sala:");

        jLabel8.setText("Precio:");

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabel9.setText("Id Funcion");

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtoncerrar.setText("Cerrar");
        jButtoncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)
                        .addComponent(jdcHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel6)
                                .addGap(76, 76, 76)
                                .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerMinutosFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboPeliculas, javax.swing.GroupLayout.Alignment.LEADING, 0, 241, Short.MAX_VALUE)
                                            .addComponent(jtfIdioma, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(317, 317, 317))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4)
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3d, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonActualizar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtoncerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jButtonBuscar)))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton3d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCrear))
                    .addComponent(jdcHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerMinutosFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonActualizar)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncerrar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       
        
        try{
         if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para buscar la Funcion.");
            return;
        }
        
         
         
         int id = Integer.parseInt(jTextFieldID.getText());
         Funcion funcion = funcionData.buscarFuncion(id);
         
         
         if (funcion == null) {
            
            JOptionPane.showMessageDialog(this, "No se encontró ninguna función con ese ID.");
            return;
           
        } 
           jComboPeliculas.setSelectedItem(funcion.getPelicula());
            jtfIdioma.setText(funcion.getIdioma());
            jRadioButton3d.setSelected(funcion.isEs3d());
            jRadioButtonSub.setSelected(funcion.isSubtitulado());
            LocalDate fecha = funcion.getHoraInicio().toLocalDate();
            jdcHoraInicio.setDate(java.sql.Date.valueOf(fecha));
            jSpinnerHora.setValue(funcion.getHoraInicio().getHour());
            jSpinnerMinutos.setValue(funcion.getHoraInicio().getMinute());
            jSpinnerHoraFin.setValue(funcion.getHoraFin().getHour());
            jSpinnerMinutosFin.setValue(funcion.getHoraFin().getMinute());
            jComboBoxSala.setSelectedItem(funcion.getSalaProyeccion());
            jTextFieldPrecio.setText(String.valueOf(funcion.getPrecio()));
        
            jButtonActualizar.setEnabled(true);
            jButtonEliminar.setEnabled(true);
       }catch(NumberFormatException e){
            
              JOptionPane.showMessageDialog(this, "El campo ID debe contener solo números.");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        try {
            // filtro q no esten vacios los campos 
            if (jComboPeliculas.getSelectedItem() == null || jComboBoxSala.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una película y una sala.");
            return;
            }
        
            if (jtfIdioma.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un idioma.");
            return;
            }
        
            if (jdcHoraInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
            return;
            }
        
            if (jTextFieldPrecio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un precio.");
            return;
            }

            Funcion funcion = new Funcion();
            
            funcion.setPelicula((Pelicula)jComboPeliculas.getSelectedItem());
            funcion.setIdioma(jtfIdioma.getText());
            funcion.setEs3d(jRadioButton3d.isSelected());
            funcion.setSubtitulado(jRadioButtonSub.isSelected());
            
            Date fechaseleccionada = jdcHoraInicio.getDate();
            LocalDate fecha = fechaseleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            int hora = (Integer) jSpinnerHora.getValue();
            int minuto = (Integer) jSpinnerMinutos.getValue();
            
            LocalDateTime fechaHoraInicio = LocalDateTime.of(fecha.getYear(),fecha.getMonthValue() , fecha.getDayOfMonth(), hora, minuto);
            
            funcion.setHoraInicio(fechaHoraInicio);
            
            int hora2 = (Integer) jSpinnerHoraFin.getValue();
            int minuto2 = (Integer) jSpinnerMinutosFin.getValue();
            
            LocalDateTime fechaHoraFin = LocalDateTime.of(fecha.getYear(),fecha.getMonthValue() , fecha.getDayOfMonth(), hora2, minuto2);
            
            funcion.setHoraFin(fechaHoraFin);
                     
            
            funcion.setSalaProyeccion((Sala)jComboBoxSala.getSelectedItem());
            
            Sala sala = (Sala)jComboBoxSala.getSelectedItem();
            
            double precio = Double.parseDouble(jTextFieldPrecio.getText());
            
            funcion.setPrecio(precio);
            
            
            funcionData.guardarFuncion(funcion);
            
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la funcion");
        }
        
        
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtoncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtoncerrarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
       try{
        if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para buscar la Funcion.");
            return;
        }
        
         
         
         int id = Integer.parseInt(jTextFieldID.getText()); 
        
        Funcion funcion = new Funcion();
        funcion.setIdFuncion(id);
        funcion.setPelicula((Pelicula) jComboPeliculas.getSelectedItem());
        funcion.setIdioma(jtfIdioma.getText());
        funcion.setEs3d(jRadioButton3d.isSelected());
        funcion.setSubtitulado(jRadioButtonSub.isSelected());

        Date fechaSeleccionada = jdcHoraInicio.getDate();
        LocalDate fecha = fechaSeleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        int horaInicio = (Integer) jSpinnerHora.getValue();
        int minutoInicio = (Integer) jSpinnerMinutos.getValue();
        int horaFin = (Integer) jSpinnerHoraFin.getValue();
        int minutoFin = (Integer) jSpinnerMinutosFin.getValue();

        LocalDateTime inicio = LocalDateTime.of(fecha, java.time.LocalTime.of(horaInicio, minutoInicio));
        LocalDateTime fin = LocalDateTime.of(fecha, java.time.LocalTime.of(horaFin, minutoFin));

        if (fin.isBefore(inicio)) {
            JOptionPane.showMessageDialog(this, "La hora de fin no puede ser anterior al inicio.");
            return;
        }

        funcion.setHoraInicio(inicio);
        funcion.setHoraFin(fin);
        funcion.setSalaProyeccion((Sala) jComboBoxSala.getSelectedItem());
        funcion.setPrecio(Double.parseDouble(jTextFieldPrecio.getText()));

        funcionData.actualizarFuncion(funcion);
        limpiarCampos(); 

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID y el precio deben ser valores numéricos válidos.");
    } 
     
   
   
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       
        
        try {
        if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para eliminar la función.");
            return;
        }

        int id = Integer.parseInt(jTextFieldID.getText());

        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que desea eliminar la función con ID " + id + "?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            funcionData.eliminarFuncion(id);
            limpiarCampos(); 
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.");
    }
        
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtoncerrar;
    private javax.swing.JComboBox<Sala> jComboBoxSala;
    private javax.swing.JComboBox<Pelicula> jComboPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3d;
    private javax.swing.JRadioButton jRadioButtonSub;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerHoraFin;
    private javax.swing.JSpinner jSpinnerMinutos;
    private javax.swing.JSpinner jSpinnerMinutosFin;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPrecio;
    private com.toedter.calendar.JDateChooser jdcHoraInicio;
    private javax.swing.JTextField jtfIdioma;
    // End of variables declaration//GEN-END:variables

    private void cargarPeliculas(){
        for (Pelicula peli : listaPelicula) {
            jComboPeliculas.addItem(peli);
        }
    
        
        
    }

    private void cargarSalas(){
        for (Sala salita : listaSalas) {
            jComboBoxSala.addItem(salita);
        }
    
    }
    
    
    private void limpiarCampos() {
  
    jTextFieldID.setText("");
    jtfIdioma.setText("");
    jTextFieldPrecio.setText("");

   
    jComboPeliculas.setSelectedIndex(-1); 
    jComboBoxSala.setSelectedIndex(-1);

   
    jRadioButton3d.setSelected(false);
    jRadioButtonSub.setSelected(false);

   
    jdcHoraInicio.setDate(null);

   
    jSpinnerHora.setValue(0);
    jSpinnerMinutos.setValue(0);
    jSpinnerHoraFin.setValue(0);
    jSpinnerMinutosFin.setValue(0);
}
}
