/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import Modelo.DetalleTicket;
import Modelo.Funcion;
import Modelo.Lugar;
import Modelo.TicketCompra;
import Persistencia.CompradorData;
import Persistencia.DetalleTicketData;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import Persistencia.TicketCompraData;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author arceb
 */
public class VistaDetalleTicket extends javax.swing.JFrame {
    
    FuncionData funcionData = new FuncionData();
    CompradorData compradorData = new CompradorData();
    DetalleTicketData detalleData = new DetalleTicketData();
    LugarData lugarData = new LugarData();
    TicketCompraData ticketCompraData = new TicketCompraData();
    
    private List<Lugar> lugaresDisponibles = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaDetalleTicket.class.getName());
    
    

    /**
     * Creates new form VistaDetalleTicket
     */
    public VistaDetalleTicket() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cargarComboFunciones();
        cargarComboCompradores();
        
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxFuncion = new javax.swing.JComboBox<>();
        jComboBoxCompradores = new javax.swing.JComboBox<>();
        jButtonCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelButacas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionActionPerformed(evt);
            }
        });

        jComboBoxCompradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCompradoresActionPerformed(evt);
            }
        });

        jButtonCompra.setText("Confirmar compra");
        jButtonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompraActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione la funcion:");

        jLabel2.setText("Cliente:");

        jLabelCantidad.setText("*");

        jLabelTotal.setText("*");

        jLabelPrecio.setText("*");

        jPanelButacas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelButacas.setMaximumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jPanelButacasLayout = new javax.swing.GroupLayout(jPanelButacas);
        jPanelButacas.setLayout(jPanelButacasLayout);
        jPanelButacasLayout.setHorizontalGroup(
            jPanelButacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        jPanelButacasLayout.setVerticalGroup(
            jPanelButacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelButacas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jButtonCompra))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jComboBoxFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCompradores, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCompradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabelCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addComponent(jButtonCompra))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionActionPerformed
        // TODO add your handling code here:
        
        Funcion funcionselec = (Funcion) jComboBoxFuncion.getSelectedItem();
        
        if(funcionselec != null){
            
            lugaresDisponibles.clear();
            
            jLabelCantidad.setText("Cantidad: 0");
            jLabelTotal.setText("Total: $0.00");
            
            crearButacas(funcionselec.getIdFuncion());
            
            // quiero ver si funciona agregar el precio
            jLabelPrecio.setText(String.format("Precio: $%.2f", funcionselec.getPrecio()));
            
            
            //iniciamos los label

            jLabelCantidad.setText("Cantidad: 0");
            jLabelTotal.setText("Total: $0.00");
        }
        
    }//GEN-LAST:event_jComboBoxFuncionActionPerformed

    private void jButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompraActionPerformed
        // TODO add your handling code here:
        Funcion funcionselec = (Funcion) jComboBoxFuncion.getSelectedItem();
        Comprador compradorSelec = (Comprador) jComboBoxCompradores.getSelectedItem();
        
        if(funcionselec == null || compradorSelec == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una funcion y un cliente");
            return;
        }
        
        if(lugaresDisponibles == null || lugaresDisponibles.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una butaca");
            return;
        }
        
        double precio = funcionselec.getPrecio();
        double total = precio * lugaresDisponibles.size();
        DetalleTicket detalle = new DetalleTicket();
         
            
            detalle.setFuncion(funcionselec);
            detalle.setSubtotal(precio);
            if(lugaresDisponibles.size() == 1){
                detalle.setLugar(lugaresDisponibles.get(0));
                detalle.setCantidad(null);
            }else if(lugaresDisponibles.size() == 2){
                detalle.setLugar(lugaresDisponibles.get(0));
                detalle.setCantidad(lugaresDisponibles.get(1));
            }
            
            
            detalleData.guardarDetalleTicket(detalle);
            for (Lugar lu : lugaresDisponibles) {
                lu.setEstado(false);
                lugarData.darBajaLugar(lu.getIdLugar());
        }
            
            
            
        int idDetalleGenerado = detalle.getIdDetalleTicket();
        System.out.println("Detalle guardado con ID: " + detalle.getIdDetalleTicket());
        TicketCompra ticket = new TicketCompra();
        ticket.setFechaCompra(LocalDate.now());
        ticket.setFechaFuncion(funcionselec.getHoraInicio());
        ticket.setMonto(total);
        ticket.setComprador(compradorSelec);
        ticket.setDetalleticket(detalle);
        
        ticketCompraData.guardarTicketCompra(ticket);
        
        DetalleTicket det = ticket.getDetalleticket();
        
        String butacas = det.getLugar().getFila() + String.valueOf(det.getLugar().getNum());
        if (det.getCantidad() != null) {
        butacas += ", " + det.getCantidad().getFila() + det.getCantidad().getNum();
        }

    String mensaje = "===== CINEMACENTRO =====\n\n"
            + "TICKET DE COMPRA\n"
            + "-----------------------------\n"
            + "Comprador: " + ticket.getComprador().getNombre() + "\n"
            + "Película: " + det.getFuncion().getPelicula().getTitulo() + "\n"
            + "Sala: " + det.getFuncion().getSalaProyeccion().getNroSala() + "\n"
            + "Horario: " + det.getFuncion().getHoraInicio() + "\n"
            + "Butacas: " + butacas + "\n"
            + "-----------------------------\n"
            + "Total: $" + ticket.getMonto() + "\n"
            + "Fecha compra: " + ticket.getFechaCompra() + "\n"
            + "-----------------------------\n\n"
            + " ¡Gracias por elegir Cinemacentro!";

    JTextArea textArea = new JTextArea(mensaje);
    textArea.setEditable(false);
    textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 14));

    JScrollPane scroll = new JScrollPane(textArea);
    scroll.setPreferredSize(new java.awt.Dimension(350, 300));

    int opcion = JOptionPane.showOptionDialog(
            this,
            scroll,
            "Ticket generado",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            new Object[]{"Imprimir", "Cerrar"},
            "Imprimir"
    );

    if (opcion == 0) {
        JOptionPane.showMessageDialog(this, "Ticket impreso con éxito ");
    }

    ///limpiamos
    lugaresDisponibles.clear();
    crearButacas(funcionselec.getIdFuncion());
    jLabelCantidad.setText("Cantidad: 0");
    jLabelPrecio.setText("Precio: $0.00");
    jLabelTotal.setText("Total: $0.00");
    }//GEN-LAST:event_jButtonCompraActionPerformed

    private void jComboBoxCompradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCompradoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCompradoresActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCompra;
    private javax.swing.JComboBox<Comprador> jComboBoxCompradores;
    private javax.swing.JComboBox<Funcion> jComboBoxFuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelButacas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void crearButacas(int idFuncion){
        
        jPanelButacas.removeAll(); //Limpiamos el panel
        LugarData lugarData = new LugarData();
        
        List<Lugar> lugares = lugarData.buscarLugaresPorFuncion(idFuncion);
        
        int columnas = 4;
        jPanelButacas.setLayout(new GridLayout(0, columnas, 10, 10));
        
        for (Lugar lu : lugares) {
           JButton boton = new JButton(lu.getFila() + String.valueOf(lu.getNum()));
           boton.setPreferredSize(new Dimension (50, 40));
           //Si esta ocupado 
           if(!lu.isEstado()){
               boton.setBackground(Color.red);
               boton.setEnabled(false);
           }else{
               //si esta libre
               boton.setBackground(Color.GREEN);
               boton.addActionListener(e -> {if(lugaresDisponibles.contains(lu)){
                lugaresDisponibles.remove(lu);
                boton.setBackground(Color.GREEN);
               }else{
                   if(lugaresDisponibles.size() < 2){
                       lugaresDisponibles.add(lu);
                       boton.setBackground(Color.BLUE);
                   }else{
                       JOptionPane.showMessageDialog(this, "Solo puede seleccionar 2 asientos");
                   }
                   
                     
               }
                        jLabelCantidad.setText("Cantidad: " + lugaresDisponibles.size());
                        double precio = funcionData.buscarFuncion(idFuncion).getPrecio();
                        jLabelPrecio.setText("Precio: $" + precio);
                        double total = precio * lugaresDisponibles.size();
                        jLabelTotal.setText(String.format("Total: $%.2f", total));
               });
           } jPanelButacas.add(boton);
        } jPanelButacas.revalidate();
          jPanelButacas.repaint();
          
    }
    
    private void cargarComboFunciones(){
        jComboBoxFuncion.removeAllItems();
        List<Funcion> funcion = funcionData.listarFuncion();
        
            for (Funcion fun : funcion) {
            jComboBoxFuncion.addItem(fun);
        }
    }
    
    private void cargarComboCompradores(){
        jComboBoxCompradores.removeAllItems();
        List<Comprador> comprador = compradorData.listarCompradores();
        
        for (Comprador compra : comprador) {
            jComboBoxCompradores.addItem(compra);
        }
    
    }

}
